CREATE DATABASE Biblioteca_project_v3
GO
USE Biblioteca_project_v3
GO

/*** Criando as tabelas***/

CREATE TABLE CLIENTE
(
id_cliente int NOT NULL IDENTITY,
nome varchar(50) NOT NULL,
bairro varchar(50) NOT NULL,
rua varchar(50) NOT NULL,
numero int NOT NULL,
complemento varchar(50) NULL,
CONSTRAINT PK_cliente PRIMARY KEY (id_cliente),
CONSTRAINT AK_nome_cliente UNIQUE (nome)

)

CREATE TABLE NACIONALIDADE
(
id_nacionalidade int NOT NULL IDENTITY,
nome_país varchar(50) NOT NULL,
id_cliente int NOT NULL,
CONSTRAINT FK_nacional_cliente FOREIGN KEY(id_cliente) REFERENCES CLIENTE,
CONSTRAINT PK_nacionalidade PRIMARY KEY(id_nacionalidade,id_cliente)
)

CREATE TABLE EMPRESTIMOS
(
id_emprest int NOT NULL IDENTITY,
valor_multa varchar(50) NOT NULL,
data_retirada int NOT NULL,
data_devolucao varchar(50) NOT NULL,
id_cliente int NOT NULL,
CONSTRAINT PK_emprestimo PRIMARY KEY (id_emprest),
CONSTRAINT FK_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTE
)

CREATE TABLE CLI_EMP
(
id_emprest int NOT NULL,
id_cliente int NOT NULL,
CONSTRAINT FK_CLI FOREIGN KEY(id_cliente) REFERENCES CLIENTE,
CONSTRAINT FK_EMP FOREIGN KEY(id_emprest) REFERENCES EMPRESTIMOS,
CONSTRAINT PK_cli_emp PRIMARY KEY(id_cliente,id_emprest)
)

CREATE TABLE EXEMPLARES
(
id_exemplares int NOT NULL IDENTITY,
id_emprest int NOT NULL,
id_cliente int NOT NULL,
estado varchar(50) NULL,
CONSTRAINT PK_exemplares PRIMARY KEY (id_exemplares),
CONSTRAINT FK_cli_emp FOREIGN KEY(id_cliente,id_emprest) REFERENCES CLI_EMP 
)

CREATE TABLE BIBLIOTECARIA
(
id_bibliotecaria int NOT NULL IDENTITY,
nome varchar(50) NOT NULL,
rg varchar(10) NOT NULL,
cpf varchar(11) NOT NULL,
salario int NULL,
id_emprest int NOT NULL,
id_exemplares int NOT NULL,
data_retirada int NOT NULL,
CONSTRAINT CK_cpf CHECK(LEN(cpf)=11),
CONSTRAINT AK_rg UNIQUE(rg),
CONSTRAINT FK_emprestimo FOREIGN KEY(id_emprest) REFERENCES EMPRESTIMOS,
CONSTRAINT FK_exemplar FOREIGN KEY (id_exemplares) REFERENCES EXEMPLARES,
CONSTRAINT FK_data_retirada FOREIGN KEY(data_retirada) REFERENCES EMPRESTIMOS,
CONSTRAINT PK_bibliotecaria PRIMARY KEY (id_bibliotecaria,id_exemplares,data_retirada),
CONSTRAINT FK_chefia_bibliotecaria FOREIGN KEY(id_bibliotecaria) REFERENCES BIBLIOTECARIA,
)

CREATE TABLE ESTANTES
(
id_estantes int NOT NULL IDENTITY,
corredor varchar(50) NOT NULL,
id_bibliotecaria int NOT NULL,
CONSTRAINT PK_estantes PRIMARY KEY (id_estantes),
CONSTRAINT FK_estantes_bibliotecaria FOREIGN KEY(id_bibliotecaria) REFERENCES BIBLIOTECARIA
)

CREATE TABLE CLI_EMP
(
id_emprest int NOT NULL,
id_cliente int NOT NULL,
CONSTRAINT FK_CLI FOREIGN KEY(id_cliente) REFERENCES CLIENTE,
CONSTRAINT FK_EMP FOREIGN KEY(id_emprest) REFERENCES EMPRESTIMOS,
CONSTRAINT PK_cli_emp PRIMARY KEY(id_cliente,id_emprest)
)

CREATE TABLE CATEGORIAS
(
id_categorias int NOT NULL IDENTITY,
descricao varchar(100) NOT NULL,
CONSTRAINT PK_categorias PRIMARY KEY (id_categorias)
)

CREATE TABLE ORGANIZACAO
(
id_exemplares int NOT NULL,
id_estantes int NOT NULL,
CONSTRAINT FK_cat_exem FOREIGN KEY(id_exemplares) REFERENCES EXEMPLARES,
CONSTRAINT FK_cat_estant FOREIGN KEY(id_estantes) REFERENCES ESTANTES,
CONSTRAINT PK_organizacao PRIMARY KEY(id_exemplares,id_estantes) 
)

CREATE TABLE LIVROS
(
id_livros int NOT NULL IDENTITY,
titulo varchar(50) NOT NULL,
ano varchar(50) NOT NULL,
volume varchar(50) NOT NULL,
paginas varchar(500) NOT NULL,
id_categorias int NOT NULL,
id_exemplares int NOT NULL,
CONSTRAINT PK_livros PRIMARY KEY (id_livros),
CONSTRAINT CK_ano CHECK (LEN(ano)=4),
CONSTRAINT CK_vol CHECK (LEN(volume)=2),
CONSTRAINT AK_livros_titulo UNIQUE(titulo),
CONSTRAINT FK_categorias FOREIGN KEY(id_categorias) REFERENCES CATEGORIAS,
CONSTRAINT FK_exemplares FOREIGN KEY(id_exemplares) REFERENCES EXEMPLARES
)

CREATE TABLE EDICAO
(
id_edicao int NOT NULL IDENTITY,
numero_edicao int NULL,
id_livros int NOT NULL,
CONSTRAINT FK_livros FOREIGN KEY(id_livros) REFERENCES LIVROS,
CONSTRAINT PK_edicao PRIMARY KEY(id_livros,id_edicao)
)

CREATE TABLE EDITORAS
(
id_editoras int NOT NULL IDENTITY,
nome varchar(50) NOT NULL,
rua varchar(50) NOT NULL,
bairro varchar(50) NOT NULL,
numero varchar(50) NOT NULL,
complemento varchar(50) NOT NULL,
CONSTRAINT PK_editorias PRIMARY KEY (id_editoras),
CONSTRAINT AK_editora_nome UNIQUE(nome)
)

CREATE TABLE AUTORES
(
id_autores int NOT NULL IDENTITY,
nome varchar(50) NOT NULL,
CONSTRAINT PK_autores PRIMARY KEY (id_autores),
CONSTRAINT AK_autor_nome UNIQUE(nome)
)

CREATE TABLE PUBLICACAO 
(
id_autores int NOT NULL,
id_livros int NOT NULL,
id_exemplares int NOT NULL,
id_editoras int NOT NULL,
CONSTRAINT FK_livros FOREIGN KEY(id_livros) REFERENCES LIVROS,
CONSTRAINT FK_exemplar_livro FOREIGN KEY(id_exemplares) REFERENCES EXEMPLARES,
CONSTRAINT PK_publicacao PRIMARY KEY (id_livros,id_exemplares),
CONSTRAINT FK_autores FOREIGN KEY(id_autores) REFERENCES AUTORES,
CONSTRAINT FK_editoras FOREIGN KEY(id_editoras) REFERENCES EDITORAS
)

CREATE TABLE INSTITUICAO_DE_ENSINO
(
id_inst_ens int NOT NULL IDENTITY,
nome_inst varchar(50) NOT NULL,
CONSTRAINT PK_inst_ens PRIMARY KEY (id_inst_ens),
CONSTRAINT AK_nome_inst UNIQUE(nome_inst)
)

CREATE TABLE EFETIVA
(
id_bibliotecaria int NOT NULL,
data_adm_efe varchar NOT NULL,
CONSTRAINT PK_bibliotecaria_efe PRIMARY KEY (id_bibliotecaria),
CONSTRAINT FK_biblio_efe FOREIGN KEY(id_bibliotecaria) REFERENCES BIBLIOTECARIA
)

CREATE TABLE ESTAGIARIA 
(
id_bibliotecaria int NOT NULL,
data_adm_est varchar NOT NULL,
id_inst_ens int NOT NULL,
CONSTRAINT FK_inst_ens FOREIGN KEY(id_inst_ens) REFERENCES INSTITUICAO_DE_ENSINO,
CONSTRAINT FK_biblio_esta FOREIGN KEY(id_bibliotecaria) REFERENCES BIBLIOTECARIA
)

CREATE TABLE TELEFONE
(
id_cliente int NOT NULL,
fone_1 varchar(45) NOT NULL,
fone_2 varchar(45) NOT NULL,
fone_3 varchar(45) NOT NULL,
CONSTRAINT FK_fone_cliente FOREIGN KEY(id_cliente) REFERENCES CLIENTE,
CONSTRAINT PK_fone PRIMARY KEY(id_cliente,fone_1)
)

INSERT INTO CLIENTE VALUES ('Maria do bairro', 'mangabeira','rua da coxinha', 70, 'AP 203')
INSERT INTO CLIENTE VALUES  ('João doido', 'mandacaru','rua da pastel', 34, 'AP 101')
INSERT INTO CLIENTE VALUES ('Gabriel star', 'bessa','rua do caju', 24, 'perto da praça do caju')
INSERT INTO CLIENTE VALUES ('José Aldo', 'liberdade','rua do corno', 2, 'proximo ao bar do chifre')
INSERT INTO CLIENTE VALUES ('Antonio', 'castelo branco','rua da ufpb', 98, 'AP 404')   


INSERT INTO EMPRESTIMOS VALUES ('0', '01/12/2017','15/12/2017',1)
INSERT INTO EMPRESTIMOS VALUES ('0', '01/11/2017','15/11/2017',2)
INSERT INTO EMPRESTIMOS VALUES ('0', '01/09/2017','15/09/2017',3)
INSERT INTO EMPRESTIMOS VALUES ('0', '01/07/2017','15/07/2016',4)
INSERT INTO EMPRESTIMOS VALUES ('0', '01/05/2017','15/05/2018',5)

INSERT INTO BIBLIOTECARIA VALUES ('Gerusa dos Santos','3355256', '99035525688',2000,1)
INSERT INTO BIBLIOTECARIA VALUES ('Jesse dos Anjos','5533256', '88035525699',1000,2)
INSERT INTO BIBLIOTECARIA VALUES ('Maria da Paz','5633552', '68035525899',2500,3)
INSERT INTO BIBLIOTECARIA VALUES ('Fulana Cordeiro','3535256', '55032568899',4000,4)
INSERT INTO BIBLIOTECARIA VALUES ('Gilvana das Neves','9335525', '03552568899',3000,5) 


INSERT INTO ESTANTES VALUES ('A',6)
INSERT INTO ESTANTES VALUES ('B',7)
INSERT INTO ESTANTES VALUES ('C',8)
INSERT INTO ESTANTES VALUES ('D',9)
INSERT INTO ESTANTES VALUES ('E',10) 


INSERT INTO CLI_EMP VALUES (1,5) 
INSERT INTO CLI_EMP VALUES (2,1) 
INSERT INTO CLI_EMP VALUES (3,3) 
INSERT INTO CLI_EMP VALUES (4,4) 
INSERT INTO CLI_EMP VALUES (5,2)


INSERT INTO EXEMPLARES VALUES (1,1,'BOM') 
INSERT INTO EXEMPLARES VALUES (2,2,'OTIMO') 
INSERT INTO EXEMPLARES VALUES (3,3,'BOM') 
INSERT INTO EXEMPLARES VALUES (4,4,'REGULAR') 
INSERT INTO EXEMPLARES VALUES (5,5,'RUIM') 
 

INSERT INTO CATEGORIAS VALUES ('TERROR')
INSERT INTO CATEGORIAS VALUES ('CIENCIAS')
INSERT INTO CATEGORIAS VALUES ('FILOSOFIA')
INSERT INTO CATEGORIAS VALUES ('ARTES')
INSERT INTO CATEGORIAS VALUES ('PROGRAMACAO')

INSERT INTO ORGANIZACAO VALUES (10,6)
INSERT INTO ORGANIZACAO VALUES (13,7)
INSERT INTO ORGANIZACAO VALUES (14,8)
INSERT INTO ORGANIZACAO VALUES (10,9)
INSERT INTO ORGANIZACAO VALUES (14,10)

INSERT INTO LIVROS VALUES ('Dom Quixote','1605','VOL.1','321',1,10)
INSERT INTO LIVROS VALUES ('Guerra e Paz','1869','VOL.1','321',10,13)
INSERT INTO LIVROS VALUES ('A Montanha Mágica','1924','VOL.1','321',5,14)
INSERT INTO LIVROS VALUES ('Ulisses','1922','VOL.1','321',8,10)
INSERT INTO LIVROS VALUES ('Em Busca do Tempo Perdido','1913','VOL.1','321',9,13)


INSERT INTO EDITORAS VALUES ('Sextante')
INSERT INTO EDITORAS VALUES ('Intrínseca')
INSERT INTO EDITORAS VALUES ('Globo')
INSERT INTO EDITORAS VALUES ('Buzz')
INSERT INTO EDITORAS VALUES ('Rocco')


INSERT INTO AUTORES VALUES ('Mark Manson')
INSERT INTO AUTORES VALUES ('Hal Elrod')
INSERT INTO AUTORES VALUES ('Napoleon Hill')
INSERT INTO AUTORES VALUES ('Paulo Vieira')
INSERT INTO AUTORES VALUES ('Yuval Noah Harari')

INSERT INTO PUBLICACAO VALUES (1,1,1,1)
INSERT INTO PUBLICACAO VALUES (2,2,2,2)
INSERT INTO PUBLICACAO VALUES (3,3,3,3)
INSERT INTO PUBLICACAO VALUES (4,4,4,4)
INSERT INTO PUBLICACAO VALUES (5,5,5,5)



INSERT INTO INSTITUICAO_DE_ENSINO VALUES ('IESP')
INSERT INTO INSTITUICAO_DE_ENSINO VALUES ('IFPB')
INSERT INTO INSTITUICAO_DE_ENSINO VALUES ('UFPB')
INSERT INTO INSTITUICAO_DE_ENSINO VALUES ('ASPER')
INSERT INTO INSTITUICAO_DE_ENSINO VALUES ('UNIPE')



INSERT INTO EFETIVA VALUES ('11/02/2018')
INSERT INTO EFETIVA VALUES ('15/03/2018')
INSERT INTO EFETIVA VALUES ('21/02/2015')
INSERT INTO EFETIVA VALUES ('11/12/2010')
INSERT INTO EFETIVA VALUES ('30/09/1998')


INSERT INTO ESTAGIARIA VALUES ('11/02/2018',1)
INSERT INTO ESTAGIARIA VALUES ('15/03/2018',2)
INSERT INTO ESTAGIARIA VALUES ('18/06/2018',3)
INSERT INTO ESTAGIARIA VALUES ('21/01/2019',4)
INSERT INTO ESTAGIARIA VALUES ('11/03/2019',5)